#!/bin/bash
# MAMA-AI Deployment Script

echo "🚀 MAMA-AI Deployment Options"
echo "================================="
echo ""
echo "Your backend is READY! Choose deployment:"
echo ""
echo "1. HEROKU (Recommended)"
echo "   - Install Heroku CLI: https://devcenter.heroku.com/articles/heroku-cli"
echo "   - Run: heroku create mama-ai-assistant"
echo "   - Run: git push heroku main"
echo ""
echo "2. RAILWAY (Easy)"  
echo "   - Install Node.js & Railway CLI"
echo "   - Run: railway login && railway init && railway up"
echo ""
echo "3. DIGITALOCEAN"
echo "   - Create App Platform project"
echo "   - Connect GitHub repo"
echo "   - Auto-deploy enabled"
echo ""
echo "📝 NEXT STEPS AFTER DEPLOYMENT:"
echo "================================="
echo "1. Set environment variables on your platform:"
echo "   - AFRICASTALKING_USERNAME=mama_ai"
echo "   - AFRICASTALKING_API_KEY=atsk_2d22cca6c92bc7655436ce2e1b2cab232e3f7898fe861e06584f5392e14724998bf381f4"
echo "   - AFRICASTALKING_SHORTCODE=985"
echo "   - FLASK_ENV=production"
echo ""
echo "2. Configure Africa's Talking webhooks:"
echo "   - SMS: https://your-app.herokuapp.com/sms"
echo "   - USSD: https://your-app.herokuapp.com/ussd"
echo ""
echo "3. Request USSD code from Africa's Talking"
echo ""
echo "✅ Your backend has:"
echo "   - Complete USSD & SMS handlers"
echo "   - AI-powered health assistant"
echo "   - Emergency detection"
echo "   - Multilingual support"
echo "   - Database with user management"
echo ""
echo "🎯 You're ready for production!"
